# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8590705b24b3d615bf4f0121cca268fbf09f1b43e3d9cb442f65838e3701502de8b117f1a0b751a79b9fac875bdffaec19209779a9bca6ceb1790ae34bf642b

test:
  secret_key_base: 6c7e09f4bf2a9cd3c9e93a392ccc1028dc17dbc5756c02c82501b448920e46f60c162690b31594cfe44327e0b2a5481e192f04d2977cb71234040878397dcc01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
